### ISSUE TITLE
Errata (EFCore)

### ISSUE THREAD

**Issue by abdollahkahne** [ProfessionalCSharp/ProfessionalCSharp2021#159]
> To read the data from C# code, you need to invoke BooksContext and access the Books property. With the
> ToListAsync method, a list is returned from a task so that it doesn’t block the calling thread (code file Intro/
> Program.cs):

 It does block the calling thread as you already mentioned in chapter related to LINQ

**Comment by christiannagel** [comment]
Can you add the reference where it is described that the thread is blocked? With the async modifier, the code does not continue with the next statement until it is finished, but the thread is not blocked. The calling thread is available to do some other tasks. So, the statement *it doesn't block the calling thread* is correct.

**Comment by abdollahkahne** [comment]
Thanks for your response. Apparently, I understand your point wrong. I thought you mean that in `ToList` (or `ToListAsync`) method do not return the results Until we used `foreach` loop, And I also wrongly! considered thread as blocked since it is waits until the result returned. Sorry and Thanks about your time assigned to this issue. I need to review meaning of Blocking and Non-Blocking, I think. I find the following article useful for myself and appended it here just for documentation. 
[Async-Await](https://www.pluralsight.com/guides/understand-control-flow-async-await)

**Comment by christiannagel** [comment]
@abdollahkahne - you're welcome. Chapter 11, "Tasks and Asynchronous Programming", might help as well. Page 292, "Calling an Asynchronous Method":

>... The code within this method does not continue before the `GreetingAsync` method is completed. However, you can reuse the thread that started the `CallerWithAsync` method. This thread is not blocked...

If you have more questions, you can add them to [Discussions](../discussions)
